build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    environment:
        php: 7.0
        mysql: 5.6

filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/soundmanager2*'
        - 'js/bar*'
        - 'js/sharing/berniecode*'
        - 'js/jquery*'
        - 'js/sharing/360player*'          

imports:
    - javascript
    - php
