build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    environment:
        php: 7.4.0

filter:
    excluded_paths:
        - '3rdparty/*'

imports:
    - javascript
    - php
